---
title: "Organize Data Notebook"
editor: 
  markdown: 
    wrap: 72
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

```{r}
# loading data into R

DATA <- read_fwf("data/data_raw/usa_00011.dat.gz",
         col_positions=fwf_positions(start=c(1,55,68,84,85,89,92,96,103,
                                             112,115),
                                    end=c(4,55,68,84,87,91,92,98,105,
                                          114,115),
                  col_names=c("Year","Metro","Homeland","Sex","Age",
                              "RaceD","Hispan","Ancestr1","Ancestr2","EDUCD","QRace")),
         col_types=cols(.default = "i"),
         progress=TRUE)
DATA
```

# Cleaning

```{r}
# remove allocated race variables
DATA <- subset(DATA, QRace ==0)
```

# Recoding Variables

```{r}
# Collapse Metro Variable
DATA$MetroC <- factor(ifelse(DATA$Metro==0,"Unknown",
                      ifelse(DATA$Metro==1,"not Metropolitan",
                      ifelse(DATA$Metro>=2 & DATA$Metro<=4,
                                    "Metropolitan",NA))),
levels=c("not Metropolitan","Metropolitan", "Unknown"))

table(DATA$Metro,DATA$MetroC,exclude = NULL)

# Recode and create gender variable

DATA$Gender <-factor((ifelse(DATA$Sex==2,"Woman",ifelse(DATA$Sex==1,
                                                        "Man",NA))),
levels=c("Woman","Man"))

table(DATA$Sex,DATA$Gender,exclude = NULL)

# Recode and Homeland variable

DATA$HomelandP <-factor(ifelse(DATA$Homeland==1,"No",
                               ifelse(DATA$Homeland==2,"Yes",NA)),
                        levels=c("No","Yes"))

table(DATA$Homeland,DATA$HomelandP,exclude = NULL)
# Recode and collapse EDUCD variable 

DATA$EducA <- factor(ifelse(DATA$EDUCD>=2 & DATA$EDUCD<=61, "Less than HS",
                     ifelse(DATA$EDUCD>=62 & DATA$EDUCD<=64, "HS Diploma",
                     ifelse(DATA$EDUCD>=65 & DATA$EDUCD<=100, "Some College",
                     ifelse(DATA$EDUCD>=101 & DATA$EDUCD<=116, "College",
                            NA)))),
levels=c("Less than HS","HS Diploma","Some College","College"))

table(DATA$EDUCD,DATA$EducA, exclude = NULL)

# Recode Hispan Variable
DATA$Hispanic <-factor((ifelse(DATA$Hispan==0,"non-Hispanic",
                              ifelse(DATA$Hispan>=1 & DATA$Hispan<=4,
                                     "Hispanic", NA))),
                       levels=c("non-Hispanic", "Hispanic"))
table(DATA$Hispan,DATA$Hispanic, exclude = NULL)
```

```{r}
# Recode Ancestr1 into Meso-Racial Ancestery

DATA$Rancestry1 <- factor(ifelse(DATA$Ancestr1 >= 001 & DATA$Ancestr1 <= 206 | DATA$Ancestr1 >= 800 & DATA$Ancestr1 <= 803,
                               "European",
                               ifelse(DATA$Ancestr1 == 900 | DATA$Ancestr1 == 902,
                                      "African-American",
                                      ifelse(DATA$Ancestr1 >= 913 & DATA$Ancestr1 <= 923,
                                             "American Indian",
                                             ifelse(DATA$Ancestr1 >= 700 & DATA$Ancestr1 <= 796,
                                                    "East and SEA",
                                                    ifelse(DATA$Ancestr1 >= 808 & DATA$Ancestr1 <= 870,
                                                           "Pacific Islander",
                                                           ifelse(DATA$Ancestr1 >= 210 & DATA$Ancestr1 <= 275 |
                                                                      DATA$Ancestr1 >= 360 & DATA$Ancestr1 <= 380,
                                                                      "Latin American",
                                                                      ifelse(DATA$Ancestr1 >= 300 & DATA$Ancestr1 <= 337,
                                                                             "non-Latin Caribbean",
                                                                             ifelse(DATA$Ancestr1 >= 400 & DATA$Ancestr1 <= 496,
                                                                                    "North African and Middle Eastern",
                                                                                    ifelse(DATA$Ancestr1 >= 500 & DATA$Ancestr1 <= 599,
                                                                                           "Sub-Saharan African",
                                                                                           ifelse(DATA$Ancestr1 >= 600 & DATA$Ancestr1 <= 695,
                                                                                                  "South Asian",
                                                                                                  ifelse(DATA$Ancestr1 >= 924 & DATA$Ancestr1 <= 994,
                                                                                                         "American",
                                                                                                         ifelse(DATA$Ancestr1 == 995,
                                                                                                                "Mixture", NA)))))))))))),
                     levels = c("European", "African-American", "American Indian", "East and SEA", "Pacific Islander",
                                "Latin American", "non-Latin Caribbean", "North African and Middle Eastern",
                                "Sub-Saharan African", "South Asian", "American", "Mixed"))

table(DATA$Ancestr1,DATA$Rancestry1, exclude = NULL)

# Recode Ancestr2 into Meso-Racial Ancestery

DATA$Rancestry2 <- factor(ifelse(DATA$Ancestr2 >= 001 & DATA$Ancestr2 <= 206 | DATA$Ancestr2 >= 800 & DATA$Ancestr2 <= 803,
                               "European",
                               ifelse(DATA$Ancestr2 == 900 | DATA$Ancestr2 == 902,
                                      "African-American",
                                      ifelse(DATA$Ancestr2 >= 913 & DATA$Ancestr2 <= 923,
                                             "American Indian",
                                             ifelse(DATA$Ancestr2 >= 700 & DATA$Ancestr2 <= 796,
                                                    "East and SEA",
                                                    ifelse(DATA$Ancestr2 >= 808 & DATA$Ancestr2 <= 870,
                                                           "Pacific Islander",
                                                           ifelse(DATA$Ancestr2 >= 210 & DATA$Ancestr2 <= 275 |
                                                                      DATA$Ancestr2 >= 360 & DATA$Ancestr2 <= 380,
                                                                      "Latin American",
                                                                      ifelse(DATA$Ancestr2 >= 300 & DATA$Ancestr2 <= 337,
                                                                             "non-Latin Caribbean",
                                                                             ifelse(DATA$Ancestr2 >= 400 & DATA$Ancestr2 <= 496,
                                                                                    "North African and Middle Eastern",
                                                                                    ifelse(DATA$Ancestr2 >= 500 & DATA$Ancestr2 <= 599,
                                                                                           "Sub-Saharan African",
                                                                                           ifelse(DATA$Ancestr2 >= 600 & DATA$Ancestr2 <= 695,
                                                                                                  "South Asian",
                                                                                                  ifelse(DATA$Ancestr2 >= 924 & DATA$Ancestr2 <= 994,
                                                                                                         "American",
                                                                                                         ifelse(DATA$Ancestr2 == 995,
                                                                                                                "Mixture", NA)))))))))))),
                     levels = c("European", "African-American", "American Indian", "East and SEA", "Pacific Islander",
                                "Latin American", "non-Latin Caribbean", "North African and Middle Eastern",
                                "Sub-Saharan African", "South Asian", "American", "Mixed"))

table(DATA$Ancestr2,DATA$Rancestry2, exclude = NULL)

# Remove all cases where Rancestry1 or Rancestry2 are NA

DATA <- DATA[complete.cases(DATA$Rancestry1, DATA$Rancestry2), ]
```

```{r}
#recode rancestry1 into big racial categories
DATA <- DATA %>%
  mutate(
    Rancestry1s = ifelse(Rancestry1 %in% c("European", "North African and Middle Eastern"), "White",
                         ifelse(Rancestry1 %in% c("African-American", "non-Latin Caribbean", "Sub-Saharan African"), "Black",
                         ifelse(Rancestry1 %in% c("American Indian"), "Indigenous",
                         ifelse(Rancestry1 %in% c("Pacific Islander"), "PI",
                         ifelse(Rancestry1 %in% c("East and SEA", "South Asian"), "Asian",
                         ifelse(Rancestry1 %in% c("Latin American"), "Latino", NA)))))))

table(DATA$Rancestry1,DATA$Rancestry1s, exclude = NULL)
```

```{r}
#recode rancestry2 into big raacial categories
DATA <- DATA %>%
  mutate(
    Rancestry2s = ifelse(Rancestry2 %in% c("European", "North African and Middle Eastern"), "White",
                         ifelse(Rancestry2 %in% c("African-American", "non-Latin Caribbean", "Sub-Saharan African"), "Black",
                         ifelse(Rancestry2 %in% c("American Indian"), "Indigenous",
                         ifelse(Rancestry2 %in% c("Pacific Islander"), "PI",
                         ifelse(Rancestry2 %in% c("East and SEA", "South Asian"), "Asian",
                         ifelse(Rancestry2 %in% c("Latin American"), "Latino", NA)))))))

table(DATA$Rancestry2,DATA$Rancestry2s, exclude = NULL)
```

```{r}

# Recode RaceD variable, since need to seperate PI and Asian
DATA$RaceC <- factor(ifelse(DATA$RaceD == 100, "White",
                  ifelse(DATA$RaceD == 200, "Black",
                  ifelse(DATA$RaceD >= 300 & DATA$RaceD <= 399, "Indigenous",
                  ifelse(DATA$RaceD >= 680 & DATA$RaceD <= 699 | 
                           DATA$RaceD == 630,"Pacific Islander",
                  ifelse(DATA$RaceD >= 400 & DATA$RaceD <= 679, "Asian",
                  ifelse(DATA$RaceD == 802, "White and Indigenous",
                  ifelse(DATA$RaceD == 830, "Black and Indigenous",
                  ifelse(DATA$RaceD >= 850 & DATA$RaceD <= 854,
                         "Asian and Indigenous",
                         NA)))))))))

DATA$RaceC <- factor(DATA$RaceC, levels = c("White", "Black", "Indigenous", "Pacific Islander", "Asian", "White and Indigenous","Black and Indigenous","Asian and Indigenous"))
```

```{r}
#filter for selected cases
DATA$selected_cases <- (((DATA$Rancestry1s == "Indigenous") & 
                      !(DATA$Rancestry2s == "Indigenous")) |
  ((DATA$Rancestry2s == "Indigenous") & !(DATA$Rancestry1s == "Indigenous"))) & 
  !(DATA$Rancestry1s == "PI") & !(DATA$Rancestry2s == "PI") & 
  !(DATA$Rancestry1s == "Latino") & !(DATA$Rancestry2s == "Latino")

DATA <- subset(DATA, 
  ((Rancestry1s == "Indigenous") & !(Rancestry2s == "Indigenous") |
     (Rancestry2s == "Indigenous") & !(Rancestry1s == "Indigenous")) & 
    !(Rancestry1s == "PI") & 
    !(Rancestry2s == "PI") & 
    !(Rancestry1s == "Latino") & 
    !(Rancestry2s == "Latino")
)

nrow(DATA)



DATA <- DATA |>
  mutate(race_ancestry = case_when(
    Rancestry1s == "Indigenous" & Rancestry2s == "White" ~ "Indigenous/White",
    Rancestry1s == "White" & Rancestry2s == "Indigenous" ~ "Indigenous/White",
    Rancestry1s == "Indigenous" & Rancestry2s == "Black" ~ "Indigenous/Black",
    Rancestry1s == "Black" & Rancestry2s == "Indigenous" ~ "Indigenous/Black",
    Rancestry1s == "Indigenous" & Rancestry2s == "Asian" ~ "Indigenous/Asian",
    Rancestry1s == "Asian" & Rancestry2s == "Indigenous" ~ "Indigenous/Asian",
  ))

table(DATA$race_ancestry, exclude=NULL)
table(DATA$Rancestry1s, DATA$Rancestry2s, DATA$race_ancestry)

table(DATA$RaceC, DATA$race_ancestry)

DATA <- DATA |>
  mutate(race_response = case_when(
    RaceC == "Indigenous" ~ "Indigenous Alone",
    race_ancestry == "Indigenous/Asian" & RaceC == "Asian" ~ "Other Race Alone",
    race_ancestry == "Indigenous/White" & RaceC == "White" ~ "Other Race Alone",
    race_ancestry == "Indigenous/Black" & RaceC == "Black" ~ "Other Race Alone",
    race_ancestry == "Indigenous/Asian" & RaceC == "Asian and Indigenous" ~ "Multiracial",
    race_ancestry == "Indigenous/White" & RaceC == "White and Indigenous" ~ "Multiracial",
    race_ancestry == "Indigenous/Black" & RaceC == "Black and Indigenous" ~ "Multiracial",
    TRUE ~ "Inconsistent"
  ))

DATA <- DATA |>
  mutate(race_response = factor(race_response,
                               levels=c("Other Race Alone", "Indigenous Alone",
                                        "Multiracial","Inconsistent")))

#model <- multinom(race_response~HomelandP,
                  #data=subset(DATA, race_ancestry=="Indigenous/White"))

#model <- vglm(race_response~HomelandP, "multinomial", 
#     data=subset(DATA, race_ancestry=="AIAN/White"))
#summary(model)

table(DATA$race_response)

table(DATA$race_ancestry, DATA$race_response)
  
```

```{r}
#Subset Data, make sure all variables are here
DATA <- subset(DATA, select=c("Year","Age","Gender","MetroC","HomelandP",
                       "Hispanic", "EducA","race_response","race_ancestry"))
DATA
```

```{r}
save(DATA, file=here("data","data_constructed"
                                ,"analytical_data.RData"))
```
