---
title: "Navigating Ancestry and Racial Classification Amongst Multiracial Indigenous American"
shorttitle: "Navigating Ancestry and Racial Classification"
abstract: How does proximity to a Homeland affect the racial decision-making process for those with mixed Indigenous ancestry? Can living in a rural area account for the influence of the Homeland variable? In this article I use data from the American Community Survey (ACS) from 2010 to 2020, to investigate the relationship between an individual's self-identified racial classification by estimating multinomial logistic regression models. The results indicate that living in a homeland or being of Hispanic Origin were the strongest predictors of whether a respondent would self-identify as Indigenous alone. These results reaffirm previous research related to the homeland variable as a strong indicator of Indigenous racial identification while expanding on its application by looking at an adult multiracial population.  
keywords: [Indigenous identity, Multiracial studies, Ancestry, Racial decision-making, Racial classification]
thanks: Thanks to everyone for checking this out.
reference-section-title: References
bibliography: ../bibliography/project.bib
csl: ../bibliography/apa-6th-edition.csl
format:
  aog-article-pdf:
    keep-tex: false
    include-in-header: 
      text: |
        \usepackage{dcolumn}
#  submittable-pdf:
#     keep-tex: false
#     fig-pos: "!t"
#     include-in-header: 
#       text: |
#         \usepackage{dcolumn}
  submittable-docx: default
---

```{r}
#| label: setup
#| include: false
library(here)
library(kableExtra)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
load(here("data","data_constructed","analytical_data.RData"))
```

### **Introduction**

On January 1, 1952, the Voluntary Relocation Program was launched by the Bureau of Indian Affairs (BIA) with field offices in Chicago, Salt Lake City, Denver, San Francisco, San Jose, Los Angeles, Oakland, Portland, Dallas, Tulsa, Oklahoma, St. Louis, Minneapolis, Cincinnati, Cleveland, and Joliet and Waukegan, Illinois (Kent-Stoll 2024). The BIA advertised the program as an avenue to acquire stable jobs and better housing, providing opportunities to Indigenous Americans willing to leave their rural reservations for bustling urban centers (Rosenthal 2012). Afterward in 1956, the Indian Relocation Act (Public Law 949) initiated a new program known as the Adult Vocational Training program which offered housing, job training, and placement through the BIA. The BIA thoroughly evaluated AVT program applicants because if the US government was going to pay for Indigenous Americans to gain an education and vocational skills, they wanted to “identify the applicants with the greatest potential for making a clean break from the reservation and assimilating into the city” (Rosenthal 2012: 53). 

Found the program paternalistic and when they did break the rules the program dropped them and left to struggle and left in harm’s way with no remorse (Rosenthal). This led to the eventual creation of pan-ethnic Indian groups and movements. AIM. Alcatraz. How did this influence the formation of an Indigenous identity? What was the difference between urban multiracial Indians versus rural multiracial Indians? 

Intertribal and “pan-Indian” identity is something that began to develop in many urban communities, especially regarding groups focused on activism since there was a focus on being “Indian” rather than individual tribal identities, which was an important part of the solidarity and group cohesion of activist organizations (Rosenthal, 2012). Tribal, intertribal, and “pan-Indian” identities were created together, simultaneously because of activities put on in urban communities to feel close to individuals' communities despite not necessarily being geographically close to them. It should be noted activist groups often critiqued those who chose to oppose Native American activist movements or organizations by saying they had “relinquished their Indian identity and absolved the United States of past injustices” which led to further disagreement (Rosenthal 2012:138)

How does living in a rural area account for the influence of the Homeland variable? Is there a rural vs. urban effect? What does that mean for the use of the homeland variable in future analysis?

(Liebler 2010; Lucero 2014; McKay 2021). Understanding the process whereby multiracial Indigenous people construct their identity is crucial for gaining insights into contemporary shifts in racial boundary formation and the individual considerations that shape racial identification for Indigenous and non-Indigenous Americans. 

### **The Formation of a Multiracial Indigenous Identity**

In 2010 Liebler published an article that argued that “homelands — physical places with cultural meaning — are an important component of the intergenerational transfer of a single-race identity in indigenous mixed-race families” (IPUMS USA: Descr: HOMELAND, n.d.; Liebler 2010:596). She investigates this hypothesis by estimating logistic regression models that predict the chance of the child being reported as a single-race American Indian; even going so far as to account for the racial composition of the local area, geographic isolation, family and area poverty levels, and ties to other American Indians or other people. Liebler reasons that the variable's predictive power can be attributed to the history and cultural importance of the area. While this reasoning for the predictive power is reasonable, the history of both forced and voluntary removal of Indigenous Americans from their homelands requires racial scholars to investigate if the homeland variable is useful in predicting Indigenous identity in other contexts. For example, could there potentially be an urban versus rural effect that may be interfering with the homeland variable? Is the homeland variable effective in predicting racial decision-making when it comes to adults, or is it only useful when looking at how parents negotiate their children's racial identity (Liebler 2010).

#### Regimes of Multiracial Classification

Contemporary research on multiracial identity has questioned the saliency of historically rooted racial regimes like the one-drop rule/hypodescent, and hyperdescent, which refer to when mixed-ancestry individuals are assigned to their lower social dominant monoracial ancestry group and vice versa (Iverson et al. 2022). Gullickson and Morning investigated what ‘rules’ guided the identification process for multiracial individuals and found three distinct regimes of classification: mixed-race individuals of Asian descent were more likely to identify as multiracial, those with Black/African ancestry followed the regime of hypodescent and a pattern of hyperdescent was observed for those with White and American Indian ancestry (2011). The authors further divided these regimes into ‘historical’ and new/immigrant regimes, where those with European, African, and American Indian ancestry were assigned a monoracial group and those of part Asian ancestry had a multiracial identity, indicating that ancestry matters in the classification process as well as history. However, it is important to note that these regimes are examples of racial projects, explanations of racial identities that do the ideological heavy lifting of connecting structure and meaning in the racial formation process, and there are other approaches to how racial classification is understood (Omi & Winant 2014). Racial appraisals have also been offered as one avenue of future focus, a racial classification system that focuses more on ‘observed race’ (Roth 2018). The explanation for this shift in focus is that as individuals display greater interest in how they are classified, a natural divide occurs between these self-classifications and observed race. 

The Latinization of Indigenous individuals also plays a role in the formation of a multiracial Indigenous identity. Researchers in Latinx studies have found that the education system, in particular, plays a role in this Latinization process; as Indigenous children enter the education system, their student records are changed by administrators and other school employees to reflect a Latino identity rather than their Indigenous identity, which is identified as an example of racial reformation can obscure Indigenous identities(Campbell-Montalvo 2023). Afro-Latino students and students with additional racial identities are particularly vulnerable to this Latinization process. This process is even observed in migration studies which “collude with the myth that the United States is a nation of immigrants which replicates, even if unwillingly, the settler colonial logic of erasure and elimination of Indigenous people” (Blackwell, Lopez, and Urrieta 2017:127). 

Even education is known to play a role in multiracial classification. The previous understanding was that people with higher levels of education found Indigenous identity more appealing, especially in metropolitan areas (Eschbach et al. 1998). However, more recent studies have found that except for Black Native Americans, all groups of Native Americans generally have lower levels of education and more frequently face barriers to educational attainment (Huyser, Sakamoto, and Takei 2010; Kao and Thompson 2003). 

### **Methods and Data**

#### Using Ancestry to Identify a Multiracial Indigenous Population

The goal of this research project is to identify whether the Homeland variable affects how the multiracial Indigenous population self-identifies. Furthermore, living in a rural place is also investigated as affecting racial decision-making. This is done by analyzing the race reporting of individuals who indicate Indigenous ancestry in addition to another distinct ancestry group. On the ACS, respondents are asked about their ancestry via the question “What is this person's ancestry or ethnic origin,” and have two lines to list their responses which are manually typed and inputted as their responses (Bureau, n.d.). 

For this study, the term Indigenous is used in place of the American Indian and Alaskan Native (AIAN) category for simplicity's sake as it functions as a collective term since this project does not focus on a specific Nation, reservation, group, and so on. It should be noted that this is not done to imply Indigenous people are a monolith rather is a necessity when conducting a project that seeks to find patterns of racial identification that span across individual groups as evidence of the unique role of settler colonialism in the racialization of Indigenous Peoples in the U.S.

Part of the data organization of this project required the identification of a multiracial population, specifically an Indigenous multiracial population. The Goldstein and Morning method was adopted, which relies on looking at adults' self-reported ancestry (Goldstein & Morning, 2000). This approach is beneficial since it does not rely on the race question to identify a multiracial Indigenous population, the population that is aware of their ancestral descent and allows for a detailed response due to the free response nature of the question. By using this method a different multiracial population is captured 

It is important to note that race and ancestry are two separate ideas but are interrelated. Race is generally understood as an inheritable master status that affects how an individual navigates the social world. Ancestry, however, is often more detailed yet less apparent regarding identity status, which may or may not be represented in how an individual identifies racially.  

#### Sample Selection and Data

The data used for this project was compiled from the American Community Survey (ACS) data for 2010 - 2020.  To analyze the race reporting of individuals with multiracial Indigenous heritage, the write-in ancestries from the ancestry question were used. To accomplish this the responses were “racialized’ in the same fashion as done by Gullickson & Morning (2011). Although the free response nature allows respondents to be quite detailed in their responses, they are not always consistent with Census racial options, which is evident with the over 500 unique responses to the ancestry question. To make this number more manageable, racial ancestries were simplified to align with the Office of Management and Budget’s different race categories, including white, black, American Indian or Alaskan Native, Asian, and Pacific Islander (1997). However, some ancestries did not align with the official categories of the OMB or were otherwise unclear.  These categories included Latino, Caribbean, non-Latin Caribbean, South American, Middle Eastern, American, and Mixed, with the latter being racially uninterpretable. These ancestries were combined when appropriate to fit the OMB categories better. For example, the Black ancestry group was created by combining all those whose ancestry fell under the groups of African-American, non-Latin Caribbean, and Sub-Saharan African. The Asian category included those whose ancestry fell under East, South East Asian, and South Asian. The White category included those with European, North African, and Middle Eastern ancestry. Respondents who listed their ancestry as Latino or Pacific Islander were dropped from the potential multiracial Indigenous population. The reason for dropping Latino is that it functions as an ethnic category on the Census/ACS and respondents of Latino or Hispanic origin can be of any race, so Latino does not indicate a specific racial ancestry that is easily interpretable as distinct from Indigenous or any other racial category. A similar clarity issue exists for the Pacific Islander (PI) category. Since Pacific Islanders are Indigenous to their respective nations this could create the issue of a double Indigenous ancestry group depending on how respondents perceive their ancestry and to avoid this potential discrepancy they were also excluded from the sample. 

After the final case selection was concluded the sample size was 490,172 respondents. Once this population was identified their ancestry selections were compared to their racial responses. When reviewing respondents' racial ancestry and their race response, four distinct identification patterns were identified 1) Indigenous alone, which contained respondents that listed their race solely as Indigenous regardless of their multiracial ancestry 2) Multiracial, which included respondents that selected a racial response that reflected a multiracial identity 3) non-Indigenous Race Alone, where respondents' race response did not reflect their Indigenous ancestry and selected their identity solely as the non-Indigenous race alone 4) Inconsistent, where respondents race response did not reflect their racial ancestry in any capacity. The inconsistent group was reviewed and it was found that the large majority were respondents who had listed their racial ancestry as Indigenous and Asian. Previous research on multiracial Asian classification suggests that multiracial Asians are more likely to go against historical patterns of racial classification due to the “newness” of mixed-Asian racial regimes or to go towards a multiracial identity (Gullickson & Morning 2011; Xu et al. 2021). Due to the focus on identifying patterns either towards a multiracial or Indigenous identity alone, which this group did not align with, and consisting of less than 1% of total responses, the inconsistent group was dropped from further analysis, bringing the sample to 478,680 respondents. 

#### Analytical Approach

I use several multinomial logistic regression models to estimate the relationship between racial ancestry, race response, and the predictor variables. The dependent variable has three categories of race response: Indigenous Alone, Multiracial, and non-Indigenous Race Alone. The key independent variable is racial ancestry. The predictor variables are metropolitan status (unknown status, non-metropolitan area, metropolitan area), homeland area (binary), educational attainment (less than HS diploma, HS diploma, some college, 4-year degree or more), gender (binary), Hispanic origin (binary), and age (continuous, 18+).

### **Results** 

#### Multinomial Logistic Regression Models

My research question focuses on understanding the relationship between the Homeland variable and the racial decision-making process for those with mixed Indigenous ancestry. I use the focal predictor variables to answer this question by identifying the relationship between the dependent and independent variables and the predictor variables. Each table presents coefficients, standard errors, and significance levels for the multinomial logistic regression models predicting race response with the predictor variables. The reference group separates these tables: White and Indigenous, Black and Indigenous, Asian and Indigenous. The model results compare the predicted race response of Indigenous Alone and Multiracial to non-Indigenous Race Alone with a separate table for each ancestry group. The base models of each table look at racial responses in relation to metropolitan status, the subsequent model adds Homeland status and the final model educational attainment, gender, Hispanic origin, and age. This setup creates three sets of tables with three models each for 9 models total.

#### Metropolitan Status

Metropolitan status indicates whether someone lives in a metropolitan area. For people with both White and Indigenous ancestry, living in a metropolitan area had different effects on their likelihood of identifying as Indigenous. Initially, those in metropolitan areas were 18% less likely to identify as Indigenous Alone rather than White, compared to those in non-metropolitan areas. However, when considering Homeland status (whether they lived in a traditional Indigenous homeland area), those in metropolitan areas became 20% more likely to identify as Indigenous Alone. This suggests that living in a metropolitan Homeland area is linked to a stronger Indigenous identity. Additionally, living in a metropolitan area raised the odds of identifying as multiracial rather than White by 17%, and when factoring in Homeland status, it increased by 41%.\

For respondents with both Black and Indigenous ancestry, living in a metropolitan area affects how they identify racially. Initially, living in a metro area makes them 50% less likely to identify as Indigenous than as Black. Although there is a slight tendency for metro residents to identify as multiracial, this link isn’t statistically significant.

However, when Homeland status is included, this pattern changes. Now, living in a metro area slightly reduces the likelihood (by 18%) of identifying as Indigenous over Black, though this effect is not significant in Table 2. On the other hand, living in a metro area significantly increases the odds of identifying as multiracial versus Black, by 30%.

For those with both Asian and Indigenous ancestry, the likelihood of identifying as Indigenous rather than Asian alone was 82% lower for those living in metropolitan areas and 42% lower for those who identified as multiracial instead of Asian. When Homeland status was taken into account, the chance of identifying as Indigenous instead of Asian was still 54% lower. However, the odds of identifying as multiracial versus Asian were not statistically significant, though they were 9.7% lower.

Accounting for education, gender, Hispanic origin, and age led to minimal changes across all three ancestry groups.

#### Homeland Status

Living in a location with Homeland status indicates that a respondent’s household is in an area officially designated as an American Indian, Alaska Native, or Native Hawaiian Homeland (AIANNH) area (Bureau, n.d.). For respondents with both White and Indigenous ancestry, living in a Homeland was associated with a 327% likelihood of identifying as Indigenous and a 122% likelihood of identifying as multiracial compared to identifying as White. For respondents with Black and Indigenous ancestry, living in a Homeland was associated with a 224% likelihood of identifying as Indigenous versus Black, and a 66% likelihood of identifying as multiracial versus Black, though this effect was less pronounced. The impact of Homeland status was strongest for respondents with Asian and Indigenous ancestry: living in a Homeland was associated with a 568% likelihood of identifying as Indigenous versus Asian and a 132% likelihood of identifying as multiracial versus Asian.

Accounting for education, gender, Hispanic origin, and age led to minimal changes across all three ancestry groups

#### Educational Attainment

Educational attainment significantly influences racial identification across ancestry groups, with three distinct patterns emerging once respondents attain a college degree. For individuals with both White and Indigenous ancestry, a college degree is associated with a shift away from identifying as White. Specifically, there is a 45% likelihood of identifying as Indigenous alone rather than White, and a 38% likelihood of identifying as Multiracial rather than White. Among those with Black and Indigenous ancestry, a college degree decreases the probability of identifying as Indigenous alone by 29% and increases the likelihood of a Multiracial identity by 15%. For respondents with Asian and Indigenous ancestry, earning a college degree tends to shift identification away from Indigenous alone, with a 66% decreased likelihood of identifying solely as Indigenous, favoring an Asian-alone identity instead.

#### Gender

Gender showed distinct patterns in racial identification across ancestry groups. Among those with White and Indigenous ancestry, men were slightly more likely than women to identify as either Indigenous or Multiracial rather than White, with similar likelihoods for each option (29% and 29%, respectively). For respondents with Black and Indigenous ancestry, gender did not significantly affect the likelihood of identifying as Indigenous versus Black; however, men were 28% more likely than women to identify as Multiracial rather than Black. In contrast, among those with Asian and Indigenous ancestry, men were 34% less likely than women to identify as Multiracial rather than Asian.

#### Hispanic Origin

In the ACS, Hispanic Origin refers to individuals of Hispanic/Spanish/Latino origin, where the origin is defined by the Census Bureau as ancestry, lineage, heritage, nationality group, or country of birth (Bureau, n.d.). Additionally, those of Hispanic Origin can be any race or any combination of races. For respondents with White and Indigenous ancestry who also identify as Hispanic, the likelihood of identifying as Indigenous rather than White is about 8x higher, while the likelihood of identifying as Multiracial rather than White was also positive but somewhat lower at 349%. Black and Indigenous respondents with Hispanic origin had a 4.5x greater likelihood of identifying as Indigenous alone rather than Black, with a similar positive likelihood for identifying as Multiracial rather than Black at 307%. Among respondents with Asian and Indigenous ancestry who also identified as Hispanic, the likelihood of identifying as Indigenous rather than Asian was nearly 2x higher, and identifying as Multiracial rather than Asian was 123%.

Overall, Hispanic origin increased the likelihood of identifying as Indigenous or Multiracial, with the strongest effect seen in those with White and Indigenous ancestry, followed by Black and Indigenous, and then Asian and Indigenous ancestry.

#### Age

Age as a predictor variable demonstrated minimal effects on racial response, and significant results were only observed for two ancestry groups. Amongst respondents with White and Indigenous ancestry it was observed that for every year in age, there was a minimal increase in the likelihood for respondents to identify as Indigenous rather than White by 0.2%, and as Multiracial rather than White by 0.1%

### **Discussion**

The previously discussed results demonstrated patterns that reaffirmed previous findings related to Indigenous identity and revealed unique deviations. After further reviewing metropolitan status three distinct patterns were identified concerning racial identity responses amongst the three mixed racial ancestry groups after reviewing all models. Initially, in Table 1 Model 1, it was found that living in a metropolitan area was negatively associated with identifying as Indigenous alone and that living in a metro area was more likely to indicate a multiracial identity. However, there was a noticeable change once the Homeland variable was added to the second model in Table 1. When the variable was added to the model it was estimated that for a respondent who lived in a metropolitan area that was also located in a Homeland, there was a 37% increase in the odds of them identifying as Indigenous alone versus multiracial which had increased by 24% from its original 17% to its current 41%. When reviewing Table 2  it was found that for those with Black and Indigenous ancestry, living in a metropolitan area was associated with a different pattern. These respondents tended to move away from an Indigenous identity and towards identifying as Black alone. In contrast, a multiracial identity remained an option at a similar association rate, meaning the one-drop rule appeared to have some saliency in some cases but not all. In Table 3 respondents with Asian and Indigenous ancestry, living in a metropolitan area correlated with a tendency to move away from identifying with their Indigenous ancestry and towards identifying exclusively as Asian rather than multiracial or Indigenous alone. However, once the Homeland variable was added to the second model in Table 3 the likelihood of respondents identifying as Indigenous alone rose by 28% and the likelihood of identifying as multiracial rose by 33% although not significant.

\
Additionally, being of Hispanic or Latino origin emerges as a significant predictor of identifying as Indigenous alone. This trend aligns with broader processes of racial classification that shape multiracial Indigenous identity, as discussed in the context of regimes of multiracial classification. The Latinization of Indigenous individuals, particularly within institutional settings like the education system, underscores how identity can be administratively reshaped. These shifts reveal the dual pressures faced by Indigenous people of Hispanic or Latino origin, as both self-identification and institutional classifications are shaped by a racial formation process that does not fully account for the complexity of Indigenous identity. Thus, for Hispanic or Latino Indigenous individuals, identifying as Indigenous alone can serve as a counteraction to these erasures, a means of reasserting their Indigenous identity in a system inclined to categorize them as part of a broader Latino group. This finding connects to the regimes of multiracial classification, where ancestry and historical context both play a critical role in the classification process, impacting Indigenous identity formation amid broader racial and institutional forces.

### **Conclusion**

These findings reinforce that Indigenous identity formation is complex, multifaceted, and shaped by both personal and structural influences. Metropolitan residency generally encourages multiracial identification across mixed ancestry groups, yet the Homeland variable shifts this dynamic significantly. When individuals live in metropolitan areas that overlap with designated Homelands, there’s an increased likelihood of identifying as Indigenous alone, emphasizing the deep relational role of Homeland in maintaining Indigenous identity. Unlike conventional geographic markers, the Homeland variable reflects a powerful cultural connection to the land as a site for cultural continuity, learning, and identity transmission.

Moreover, being of Hispanic or Latino origin strengthens the likelihood of identifying as Indigenous alone, underscoring how individuals resist broader systems that tend to conflate Indigenous and Latino identities. The Latinization process within institutions such as education often obscures Indigenous identity, yet self-identification as Indigenous alone emerges as a way to affirm and reclaim this heritage. These findings collectively illustrate how Indigenous identity in the U.S. exists within—and adapts to—frameworks that both challenge and reinforce historical and social classifications, revealing a resilient identity process that holds fast even within evolving racial regimes and institutional pressures.
